#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pymachinery
Version  : 0.1.3
Release  : 1
URL      : https://files.pythonhosted.org/packages/0f/e1/399f29f9ab3a22e7e8e8a401053be677b4ae9e15ef3f7f35cc35becd039a/pymachinery-0.1.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/0f/e1/399f29f9ab3a22e7e8e8a401053be677b4ae9e15ef3f7f35cc35becd039a/pymachinery-0.1.3.tar.gz
Summary  : Python workers for RichardKnop/machinery
Group    : Development/Tools
License  : MIT
Requires: pypi-pymachinery-python = %{version}-%{release}
Requires: pypi-pymachinery-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(pymongo)
BuildRequires : pypi(redis)

%description
# Machinery Python SDK
[PyPI](https://pypi.org/project/pymachinery/)
This is a subset Python implementation of a worker for `RichardKnop/machinery`.

%package python
Summary: python components for the pypi-pymachinery package.
Group: Default
Requires: pypi-pymachinery-python3 = %{version}-%{release}

%description python
python components for the pypi-pymachinery package.


%package python3
Summary: python3 components for the pypi-pymachinery package.
Group: Default
Requires: python3-core
Provides: pypi(pymachinery)
Requires: pypi(pymongo)
Requires: pypi(redis)

%description python3
python3 components for the pypi-pymachinery package.


%prep
%setup -q -n pymachinery-0.1.3
cd %{_builddir}/pymachinery-0.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646326527
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
